### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by bastien-md** [bastien-md/codepath-todo-app#1]
My app is complete - please review. /cc @codepathreview @codepath
One question: I set an onClickListener on the item's imageView in the CustomArrayAdapter class. Is that the right place to use it and is it good practice to use an interface in the adapter like I did?

**Comment by nesquena** [comment]
Bastien,

Thanks for applying and submitting your pre-work. Based on your LinkedIn it is unclear if you meet the [selection criteria for participating in the course](http://courses.codepath.com/snippets/intro_to_android/selection_criteria). In particular:

* Within past 3 years have been employed as a software engineer, team lead, technical founder, VPE
* 2+ years of professional software development experience (average participant has 5+ years)
* Sustained professional software experience at companies involving shipping production code strongly preferred

Can you review that and let me know if you can confirm that you meet the requirements? If not, I can add you as a "remote self-paced observer" so you can still have access to the curriculum and learn at your pace. In the meantime, you should also check out the [resources we provide here](http://courses.codepath.com/snippets/intro_to_android/email_faq#heading-i-dont-have-much-or-any-professional-software-development-experience-how-can-codepath-help-me).

**Comment by bastien-md** [comment]
Hi Nathan,

Thanks for getting back quickly.
Let me clarify -

I have one year left on my Bachelors of Electrical and Electronic Degree in
the UK. I have been learning Java for two years now.

I took a year out of university and have been working at Cisco as a
Software Engineer since last July.

Prior to this, I worked for a year on the implementation of a software
project. The work revolved a lot around WordPress, HTML / CSS and
JavaScript.

So all in all I have just below 2 years professional experience. As I
applied to this bootcamp, I knew that I was not far off from that
requirement.

I really hope my motivation and work ethic balance out the "lack" of
experience in the selection process. This also explains why I made the two
apps. Such programmes do not exist back home so I really want to make the
most of my time here in the Bay Area!

So to answer your question, in all honesty I do not meet one criteria. That
being said, if nothing can be done please add me as a remote observer.

I look forward to hearing back!

Many thanks,
Bastien

**Comment by nesquena** [comment]
Thanks for the detailed explanation, I appreciate the additional details. Great to see you were able to complete many extension tasks. The extension tasks available on each project are often the most valuable learnings since they dive deeper into common real-world Android use cases. 

Can you **schedule a short 10 minute phone conversation** with us for either tomorrow or early next week? Navigate to [using this calendar](https://calendar.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU) and choose a 15-minute slot. Let us know if none of those times work.

Once you select a slot, can you make sure to **include best number** to reach you at to the invite? Look forward to chatting soon!

**Comment by bastien-md** [comment]
Hi Nathan,

Much appreciated. I have booked for next week Tuesday at 11am - I can't do
tomorrow unfortunately.

Looking forward to speaking then!
